version: "3.9"
x-app: &app-config
  image: soccer-manager-dev
  build:
    context: .
  restart: always
  volumes:
    - .:/code
    - dev-static-data:/vol/web
  env_file:
    - .env


services:
  app:
    # build:
    #   context: .
    #   args:
    #     - DEV=true
    # volumes:
    #   - .:/code
    #   - dev-static-data:/vol/web
    # env_file:
    #   - .env
    <<: *app-config
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  redis:
    image: "redis:6.2.5-alpine"
    ports:
      - "6379:6379"

  celeryworkers:
    <<: *app-config
    command: >-
      celery -A config worker -l DEBUG
    depends_on:
      - redis
      - db

volumes:
  dev-db-data:
  dev-static-data:
