# Generated by Django 5.0 on 2024-01-04 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import soccer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("country", models.CharField(max_length=50)),
                ("budget", models.DecimalField(decimal_places=2, default=5000000, max_digits=11)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("goalkeeper", "Goalkeeper"),
                            ("defender", "Defender"),
                            ("midfielder", "Midfielder"),
                            ("attacker", "Attacker"),
                        ],
                        max_length=50,
                    ),
                ),
                ("age", models.IntegerField(default=soccer.models.get_random_age)),
                ("country", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("market_value", models.DecimalField(decimal_places=2, default=1000000, max_digits=10)),
                ("transferable", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="players", to="soccer.team"
                    ),
                ),
            ],
        ),
    ]
